name: Secret Back Sync Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for syncing secrets (options: dev, staging, prod)'
        type: string
        required: true
      reponame:
        description: 'Target repository name for syncing secrets'
        type: string
        required: true
      dry_run:
        description: 'Enable dry run mode to preview changes without making them'
        type: boolean
        required: true

jobs:
  # Job for syncing secrets to the DEV environment
  sync-dev:
    timeout-minutes: 2
    name: Secret Sync DEV
    if: ${{ inputs.environment == 'dev'}}
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses:  NediCorp/action-secrets-sync@v1.0.0
        name: sync-secrets Dev
        continue-on-error: false
        with:
          dry_run: ${{ inputs.dry_run }}
          secrets: |
            AWS_ASSUME_ROLE
            AWS_REGION
            AWS_KUBECONFIG
            KONG_HOST
            KEYCLOAK_HOST
          repositories: |
            \${{ inputs.reponame }}\b
          environment: development
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN_CLASSIC }}
        env:
          AWS_ASSUME_ROLE: ${{secrets.AWS_ASSUME_ROLE}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KUBECONFIG: ${{secrets.AWS_KUBECONFIG}}
          KONG_HOST:  ${{secrets.KONG_HOST}}
          KEYCLOAK_HOST:  ${{secrets.KEYCLOAK_HOST}}

  # Job for syncing secrets to the QA environment
  sync-qa:
    timeout-minutes: 2
    name: Secret Sync QA
    if: ${{ github.event.inputs.environment == 'qa'}}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses:  NediCorp/action-secrets-sync@v1.0.0
        name: sync-secrets QA
        continue-on-error: false
        with:
          dry_run: ${{ inputs.dry_run }}
          secrets: |
            AWS_ASSUME_ROLE
            AWS_REGION
            AWS_KUBECONFIG
            KONG_HOST
            KEYCLOAK_HOST
          repositories: |
              \${{ inputs.reponame }}\b
          environment: staging
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN_CLASSIC }}
        env:
          AWS_ASSUME_ROLE: ${{secrets.AWS_ASSUME_ROLE}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KUBECONFIG: ${{secrets.AWS_KUBECONFIG}}
          KONG_HOST:  ${{secrets.KONG_HOST}}
          KEYCLOAK_HOST:  ${{secrets.KEYCLOAK_HOST}}

  # Job for syncing secrets to the PROD environment
  sync-prod:
    timeout-minutes: 2
    name: Secret Sync PROD
    if: ${{ inputs.environment == 'prod'}}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses:  NediCorp/action-secrets-sync@v1.0.0
        name: sync-secrets Prod
        continue-on-error: false
        with:
          dry_run: ${{ inputs.dry_run }}
          secrets: |
            AWS_ASSUME_ROLE
            AWS_REGION
            AWS_KUBECONFIG
            KONG_HOST
            KEYCLOAK_HOST
          repositories: |
            \${{ inputs.reponame }}\b
          environment: production
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN_CLASSIC }}
        env:
          AWS_ASSUME_ROLE: ${{secrets.AWS_ASSUME_ROLE}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KUBECONFIG: ${{secrets.AWS_KUBECONFIG}}
          KONG_HOST:  ${{secrets.KONG_HOST}}
          KEYCLOAK_HOST:  ${{secrets.KEYCLOAK_HOST}}